apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      nodeSelector:
        gpu_memory: "{{ .Values.gpuMemory }}"
        node: "{{ .Values.nodeSelector.node }}"
      runtimeClassName: nvidia
      tolerations:
        - key: "gpu_memory"
          value: "{{ .Values.gpuMemory }}"
          effect: "NoSchedule"
        - key: "node"
          value: "{{ .Values.nodeSelector.node }}"
          effect: "NoSchedule"
      initContainers:
      - name: wait-for-cache
        image: public.ecr.aws/c9r4x6y5/eyelevel/busybox:latest
        imagePullPolicy: "Always"
        command: ['sh', '-c', "until nc -z {{ .Values.dependencies.cache }}; do echo waiting for cache; sleep 2; done"] 
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pull }}"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        workingDir: /workspace
        command:
          - /bin/sh
          - -c
          - |
            export PYTHONPATH=/workspace && supervisord -c /workspace/supervisord.conf
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep 'summary.celery.appSummary' || exit 1
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep 'summary.celery.appSummary' || exit 1
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
            nvidia.com/gpu: {{ .Values.resources.limits.gpu }}
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
            nvidia.com/gpu: {{ .Values.resources.requests.gpu }}
        volumeMounts:
        - name: config-volume
          mountPath: /workspace/config.py
          subPath: config.py
        - name: supervisord-volume
          mountPath: /workspace/supervisord.conf
          subPath: supervisord.conf
      volumes:
      - name: config-volume
        configMap:
          name: summary-config-py-map
      - name: supervisord-volume
        configMap:
          name: summary-supervisord-24gb-conf-map