apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-redis-server
  template:
    metadata:
      labels:
        app: flask-redis-server
    spec:
      containers:
        - name: flask-redis-server
          image: admin-server
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-redis-server-service
spec:
  type: LoadBalancer
  selector:
    app: flask-redis-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
