apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: admin-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server-service
spec:
  type: LoadBalancer
  selector:
    app: admin-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
