apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: file-post-process
  labels:
    strimzi.io/cluster: "{{ .Release.Name }}-cluster"
spec:
  partitions: {{ .Values.service.partitions }}
  replicas: {{ .Values.service.replicas }}
  config:
    retention.ms: 7200000
    retention.bytes: {{ .Values.service.retention_bytes }}
    segment.bytes: {{ .Values.service.segment_bytes }}