apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Values.service.name }}"
  labels:
    app: "{{ .Values.service.name }}"
spec:
  serviceName: "{{ .Values.service.name }}"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.service.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.service.name }}"
    spec:
      serviceAccountName: "{{ .Values.service.name }}-sa"
      containers:
      - name: "{{ .Values.service.name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.port }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          fsGroup: {{ .Values.securityContext.fsGroup }}
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.service.name }}-secret"
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.service.name }}-secret"
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.service.name }}-secret"
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.service.name }}-secret"
              key: MYSQL_DATABASE
        volumeMounts:
        - name: "{{ .Values.service.name }}-persistent-storage"
          mountPath: "{{ .Values.persistence.mountPath }}"
        - name: my-cnf
          mountPath: /etc/my.cnf.d/my.cnf
          subPath: my.cnf
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d/init-db.sql
          subPath: init-db.sql
      volumes:
      - name: "{{ .Values.service.name }}-persistent-storage"
        persistentVolumeClaim:
          claimName: "{{ .Values.service.name }}-pvc"
      - name: my-cnf
        configMap:
          name: my-configmap
      - name: init-db
        configMap:
          name: my-configmap