apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      nodeSelector: 
        node: "{{ .Values.nodeSelector.node }}"
      tolerations:
        - key: "node"
          value: "{{ .Values.nodeSelector.node }}"
          effect: "NoSchedule"
      initContainers:
      - name: wait-for-cache
        image: public.ecr.aws/c9r4x6y5/eyelevel/busybox:latest
        imagePullPolicy: "Always"
        command: ['sh', '-c', "until nc -z {{ .Values.dependencies.cache }}; do echo waiting for cache; sleep 2; done"]
      - name: wait-for-file-storage
        image: public.ecr.aws/c9r4x6y5/eyelevel/busybox:latest
        imagePullPolicy: "Always"
        command: ['sh', '-c', "until nc -z {{ .Values.dependencies.file }}; do echo waiting for file storage; sleep 2; done"]
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pull }}"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        workingDir: /app
        command:
          - /bin/sh
          - -c
          - |
            export PYTHONPATH=/app && celery -A document.celery_process.app worker --loglevel=INFO --concurrency=1 --queues=ocr_queue -n ${POD_NAME}-w1
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep 'document.celery_process.app' | grep -v grep || exit 1
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep 'document.celery_process.app' | grep -v grep || exit 1
          initialDelaySeconds: 10
          periodSeconds: 30
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.py
          subPath: config.py
        - name: credentials-volume
          mountPath: /app/credentials.json
          subPath: credentials.json
      volumes:
      - name: config-volume
        configMap:
          name: layout-config-py-map
      - name: credentials-volume
        configMap:
          name: layout-ocr-credentials-map