apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: custom-minio:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              value: "ROOTNAME"
            - name: MINIO_ROOT_PASSWORD
              value: "CHANGEME123"
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          emptyDir: {} # Use PersistentVolume for production
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app: minio
spec:
  type: ClusterIP # Internal access within the cluster
  ports:
    - name: minio-api # Added name for the API port
      port: 9000
      targetPort: 9000
    - name: minio-console # Added name for the console port
      port: 9001
      targetPort: 9001
  selector:
    app: minio
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
data:
  MINIO_HOST: "minio-service"
  MINIO_PORT: "9000"
  MINIO_ACCESS_KEY: "ROOTNAME"
  MINIO_SECRET: "CHANGEME123"
